### ISSUE TITLE
Gdal plugin does not compile with gdal 3.6.2 (latest)

### ISSUE THREAD

**Issue by vilhelmen** [ossimlabs/ossim-plugins#55]
Something seemingly changed between gdal 3.2.2 and 3.6.2 to make the type conversion in `ossimGdalTiledDataset.cpp:476` an error, though it's not clear why. Tested with `osgeo/gdal:ubuntu-full-3.2.2` and `osgeo/gdal:ubuntu-full-3.6.2` containers:

```
[ 99%] Building CXX object ossim-plugins/gdal/src/CMakeFiles/ossim_gdal_plugin.dir/ossimGdalTiledDataset.cpp.o
/tmp/ossim-plugins/gdal/src/ossimGdalTiledDataset.cpp: In function 'void GDALRegister_MEMTiled()':
/tmp/ossim-plugins/gdal/src/ossimGdalTiledDataset.cpp:476:43: error: invalid conversion from 'MEMDataset* (*)(const char*, int, int, int, GDALDataType, char**)' to 'GDALDataset* (*)(const char*, int, int, int, GDALDataType, char**)' [-fpermissive]
  476 |         poDriver->pfnCreate = MEMDataset::Create;
      |                               ~~~~~~~~~~~~^~~~~~
      |                                           |
      |                                           MEMDataset* (*)(const char*, int, int, int, GDALDataType, char**)
```

Dockerfile build example:
```
ARG BASE_CONTAINER=osgeo/gdal:ubuntu-full-3.6.2
FROM $BASE_CONTAINER

RUN apt-get update && apt-get install -y \
  ca-certificates \
  git \
  python3-pip \
  python3-dev \
  geotiff-bin \
  libtiff-dev \
  libtiff-tools \
  libopenthreads-dev \
  libjpeg-dev \
  libgeos++-dev \
  cmake \
  libgeotiff-dev \
  libopenjp2-7-dev \
  libpng-dev \
  && rm -rf /var/lib/apt/lists/*

#  && ( git clone https://github.com/ossimlabs/ossim.git && cd ossim && git checkout OrchidIsland-2.11.1 ) \
#  && ( git clone https://github.com/ossimlabs/ossim-plugins.git && cd ossim-plugins && git checkout OrchidIsland-2.11.1 ) \
RUN mkdir /tmp/ossim && cd /tmp/ossim \
  && git clone https://github.com/ossimlabs/ossim.git \
  && git clone https://github.com/ossimlabs/ossim-plugins.git \
  && export BUILD_GDAL_PLUGIN=ON \
  && export BUILD_OPENJPEG_PLUGIN=ON \
  && export BUILD_PNG_PLUGIN=ON \
  && export BUILD_JPEG12_PLUGIN=OFF \
  && export BUILD_CNES_PLUGIN=OFF \
  && export OSSIM_MAKE_JOBS=4 \
  && export MAKE_JOBS=4 \
  && export OSSIM_INSTALL_PREFIX='/' \
  && ( ossim/scripts/build.sh && cd build && make install ) \
  && cd / && rm -rf /tmp/ossim
```

**Comment by vilhelmen** [comment]
Issue persists with latest dev branches of ossim and ossim-plugins with gdal 3.7.0. Running ortho on a JP2k NTF goes to gdal and dies with SIGSEGV
```
ossimImageHandler::loadState(kwl, prefix) DEBUG: Leaving Ok ...
ossimGdalTileSource::open() DEBUG: entered ...
Segmentation fault
```

**Comment by vilhelmen** [comment]
Fixed in ff35408b986ac9f99c9731f58935387d776ee457
